name: NIST COBOL85 tests
<<<<<<< HEAD
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested]
    
jobs:
  run-tests:
=======
on: [push]
jobs:
  check-bats-version:
>>>>>>> 4f06d3afc9c784c4a495f774fa3c94238826d6ff
    runs-on: ubuntu-latest
    steps:
      # Checkout opensource COBOL
      - name: Checkout opensource COBOL
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get update
<<<<<<< HEAD
          sudo apt-get install -y build-essential libncurses-dev libgmp-dev bison flex gettext automake autoconf
=======
          sudo apt-get install -y build-essential libncurses5 libncurses5-dev libgmp-dev bison flex gettext automake autoconf
>>>>>>> 4f06d3afc9c784c4a495f774fa3c94238826d6ff
      
      - name: Install opensource COBOL
        run: |
          cd vbisam
          ./configure --prefix=/usr/
          sudo make install
          cd ../
          ./configure --prefix=/usr/ --with-vbisam
          sudo make install
      
      - name: run NIST tests
        run: |
          cd tests/cobol85
          make test
<<<<<<< HEAD
=======

      
 
>>>>>>> 4f06d3afc9c784c4a495f774fa3c94238826d6ff
